let coffeeData = [
  {
    id: 1,
    name: "Espresso",
    price: 120,
    size: "Small",
    isHot: true,
    ingredients: ["Coffee beans", "Water"],
    rating: 4.5,
  },
  {
    id: 2,
    name: "Cappuccino",
    price: 180,
    size: "Medium",
    isHot: true,
    ingredients: ["Espresso", "Steamed Milk", "Foam"],
    rating: 4.7,
  },
  {
    id: 3,
    name: "Latte",
    price: 200,
    size: "Large",
    isHot: true,
    ingredients: ["Espresso", "Steamed Milk"],
    rating: 4.6,
  },
  {
    id: 4,
    name: "Americano",
    price: 150,
    size: "Medium",
    isHot: true,
    ingredients: ["Espresso", "Hot Water"],
    rating: 4.3,
  },
  {
    id: 5,
    name: "Mocha",
    price: 220,
    size: "Large",
    isHot: true,
    ingredients: ["Espresso", "Chocolate", "Milk"],
    rating: 4.8,
  },
  {
    id: 6,
    name: "Iced Coffee",
    price: 160,
    size: "Medium",
    isHot: false,
    ingredients: ["Coffee", "Ice", "Sugar"],
    rating: 4.2,
  },
  {
    id: 7,
    name: "Cold Brew",
    price: 190,
    size: "Large",
    isHot: false,
    ingredients: ["Cold Brew Coffee", "Ice"],
    rating: 4.6,
  },
  {
    id: 8,
    name: "Flat White",
    price: 170,
    size: "Small",
    isHot: true,
    ingredients: ["Espresso", "Steamed Milk"],
    rating: 4.4,
  },
];

export default coffeeData;
